var mongoose = require('mongoose');

var CustomersSchema = new mongoose.Schema({
  firstname:    String,
  lastname:     String,
  primaryphone: String,
  mobile:       String,
  email:        String,
  designation:  String,
  leadsource:   String,
  plantype:     String,
  speed:        String,
  landmark:     String,
  custId:       Number,
  address:      String,
  comp:         String,
  priority:     String,
  company:      String,
  status:       String,
  stage:        String,
  zone:         String,
  area:         String,
  division:     String,
  fdesc:        String,
  username:     String,
  // GPS
  lat:          Number,
  lng:          Number,
  // Feasibility
  surveyby:     String,
  surveydate:   String,
  visitstatus:  String,
  feasibility:  String,
  notfeasiblereason: String,
  distanceolt:  Number,
  nearestolt:   String,
  nearestpole:  String,
  signalstrength: String,
  fiberavailable: String,
  cablelength:  Number,
  surveynotes:  String,
  // Post Feasibility
  routesurveyby:  String,
  routesurveydate:String,
  routetype:    String,
  routelength:  Number,
  polesrequired:Number,
  jclosures:    Number,
  fiberlength:  Number,
  dropwirelength:Number,
  splittertype: String,
  ontmodel:     String,
  estimatedcost:Number,
  installcharge:Number,
  approvalstatus:String,
  approvedby:   String,
  scheduleddate:String,
  assignedtech: String,
  postfeasibilitynotes: String,
  fiberItemId:  String,
  fibercableid: String,
  fibercores:   String,
  splitterItemId:String,
  // P&C
  leadtech:     String,
  supporttech:  String,
  installdate:  String,
  installstatus:String,
  fiberused:    Number,
  dropwireused: Number,
  polesused:    Number,
  jclosuresused:Number,
  splitterinstalled: String,
  splitterloc:  String,
  ontItemId:    String,
  ontserial:    String,
  ontmac:       String,
  ponport:      String,
  onupower:     String,
  colorcode:    String,
  ipaddress:    String,
  vlanid:       String,
  bwprofile:    String,
  speedtest:    String,
  ping:         Number,
  testresult:   String,
  customeracceptance: String,
  activationdate: String,
  firstbilldate:  String,
  monthlycharge:  Number,
  installcollected: Number,
  securitydeposit:  Number,
  commissionnotes:  String,
  // Legacy fields
  jclosureloc:  String,
  olt:          String,
  pon:          String,
  splitter:     String,
  rtt:          String,
  mac:          String,
  wireid:       String,
  wiremake:     String,
  wiremeter:    String,
  nooffiber:    String,
  created_at:   { type: Date },
  updated_at:   { type: Date },
}, { strict: false });

CustomersSchema.pre('save', function() { this.created_at = new Date(); });
CustomersSchema.pre('findOneAndUpdate', function() { this.set({ updated_at: new Date() }); });

CustomersSchema.index({ company: 1, stage: 1 });
CustomersSchema.index({ company: 1, status: 1 });
CustomersSchema.index({ mobile: 1 });

module.exports = mongoose.model('customers', CustomersSchema);
